name: Docker BuildX

on: push

env:
  LATEST_ARCH: amd64
  LATEST_OS: focal

jobs:
  docker-buildx:
    strategy:
      matrix:
          arch: [amd64, arm64]
          os: [bionic, focal]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v1

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - run: echo "OS=${{ matrix.os }}, ARCHITECTURE=${{ matrix.arch }}"
      
      - name: Build and Push
        if: ${{ matrix.os != env.LATEST_OS || matrix.arch != env.LATEST_ARCH }}
        uses: docker/build-push-action@v2
        with:
          build-args: BASE_IMAGE=ubuntu:${{ matrix.os }}
          context: .
          file: Dockerfile.${{ matrix.arch }}
          platforms: linux/${{ matrix.arch }}
          push: true
          tags: atsushisaito/docker-ubuntu-vnc-desktop:${{ matrix.os }}-${{ matrix.arch }}

      - name: Build and Push
        if: ${{ matrix.os == env.LATEST_OS && matrix.arch == env.LATEST_ARCH }}
        uses: docker/build-push-action@v2
        with:
          build-args: BASE_IMAGE=ubuntu:${{ matrix.os }}
          context: .
          file: Dockerfile.${{ matrix.arch }}
          platforms: linux/${{ matrix.arch }}
          push: true
          tags: |
            atsushisaito/docker-ubuntu-vnc-desktop:${{ matrix.os }}-${{ matrix.arch }}
            atsushisaito/docker-ubuntu-vnc-desktop:latest